modLoader="javafml"
loaderVersion="[40,)" 
license="MIT License"
issueTrackerURL="https://github.com/allkillernofill3r/MoGlowstonePlus/issues"

[[mods]]
modId="moglowstoneplus"
version="1.0.0"
displayName="Mo' Glowstone Plus"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mo-glowstone-plus"
logoFile="moglowstoneplus_logo.png"
credits="Thanks to MasterGeneral156 for letting me make the addon!"
authors="allkillernofiller (Killer_Playz)"
description='''
An addon for Mo' Glowstone that adds more colorful glowstone items!
'''

[[dependencies.moglowstoneplus]]
    modId="ctdcore"
    mandatory=true
    versionRange="[2.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.moglowstoneplus]]
    modId="moglowstone"
    mandatory=true
    versionRange="[2.1,)"
    ordering="NONE"
    side="BOTH"
